const icons={home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10v10h13V10"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',bolt:'<path d="m13 2-9 12h8l-1 8 9-12h-8z"/>',leaf:'<path d="M20 4c-8 0-14 4-14 11 0 3 2 5 5 5 7 0 9-8 9-16Z"/><path d="M4 21c3-6 7-9 13-12"/>',message:'<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"/>',gift:'<path d="M20 12v9H4v-9M2 7h20v5H2zM12 7v14"/><path d="M12 7H7.5A2.5 2.5 0 1 1 10 4.5C10 7 12 7 12 7Zm0 0h4.5A2.5 2.5 0 1 0 14 4.5C14 7 12 7 12 7Z"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4"/>',chevron:'<path d="m9 18 6-6-6-6"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',plus:'<path d="M12 5v14M5 12h14"/>',play:'<path d="m8 5 11 7-11 7z"/>',video:'<rect x="3" y="5" width="14" height="14" rx="2"/><path d="m17 10 4-2v8l-4-2z"/>',send:'<path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>'};
icons.library='<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m10 9 5 3-5 3z"/>';icons.search='<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>';icons.trophy='<path d="M8 4h8v5a4 4 0 0 1-8 0z"/><path d="M8 6H4v2a4 4 0 0 0 4 4m8-6h4v2a4 4 0 0 1-4 4M12 13v4m-4 4h8m-6-4h4"/>';icons.flame='<path d="M12 22c4 0 7-3 7-7 0-3-1.5-5.5-4-8 .2 3-1 4.5-2 5-1-4-3-6-3-9-3 3-5 7-5 11 0 4.5 3 8 7 8z"/>';icons.star='<path d="m12 2 3 6 7 .9-5 4.8 1.3 6.8L12 17l-6.3 3.5L7 13.7 2 8.9 9 8z"/>';icons.medal='<circle cx="12" cy="14" r="6"/><path d="m8.5 8-3-6h5l1.5 4 1.5-4h5l-3 6m-6.5 6 2 2 4-4"/>';icons.crown='<path d="m3 7 4 4 5-7 5 7 4-4-2 11H5z"/><path d="M5 21h14"/>';icons.sun='<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>';icons.moon='<path d="M20.5 14.5A8 8 0 0 1 9.5 3.5 9 9 0 1 0 20.5 14.5Z"/>';
document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[el.dataset.icon]||''}</svg>`});
const themeToggle=document.getElementById('themeToggle');let savedTheme='dark';try{savedTheme=localStorage.getItem('form-theme')||'dark'}catch(e){}document.body.classList.toggle('light-theme',savedTheme==='light');function updateThemeButton(){const isLight=document.body.classList.contains('light-theme');themeToggle.setAttribute('aria-label',isLight?'Switch to dark theme':'Switch to light theme');themeToggle.setAttribute('aria-pressed',String(!isLight))}updateThemeButton();themeToggle.addEventListener('click',()=>{document.body.classList.toggle('light-theme');try{localStorage.setItem('form-theme',document.body.classList.contains('light-theme')?'light':'dark')}catch(e){}updateThemeButton()});
const titles={home:'Good afternoon, Alex.',bookings:'Make time for yourself.',plans:'Built around your goals.',nutrition:'Fuel the work.',messages:'Your coach is here.',vouchers:'Give something meaningful.'};
titles.videos='Learn. Move. Progress.';
titles.rewards='Make progress rewarding.';
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));document.getElementById('pageTitle').textContent=titles[id];window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));document.querySelectorAll('[data-view-link]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.viewLink)));
const dates=document.getElementById('dates');['31','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','1','2','3','4'].forEach((d,i)=>{const b=document.createElement('button');b.textContent=d;if(i===0||i>30)b.className='dim';if(d==='9'&&i===9)b.classList.add('selected');b.addEventListener('click',()=>{dates.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});dates.appendChild(b)});
const modal=document.getElementById('modal'),modalTitle=document.getElementById('modalTitle'),modalText=document.getElementById('modalText');function openModal(title,text){modalTitle.textContent=title;modalText.textContent=text;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-start]').forEach(b=>b.addEventListener('click',()=>openModal('Ready to train?','Your 48-minute Lower Body Power session is loaded, with guided sets, rest timers and form cues.')));document.querySelectorAll('[data-video]').forEach(b=>b.addEventListener('click',()=>openModal(`${b.dataset.video} demo`,'Your coach’s technique video is ready. Watch the movement, then follow the cues at your own pace.')));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const toast=document.getElementById('toast');function notify(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2800)}
document.querySelector('[data-message]').addEventListener('click',()=>showView('messages'));document.getElementById('newBooking').addEventListener('click',()=>notify('Booking options are ready to choose.'));
const form=document.getElementById('messageForm');form.addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('messageInput'),value=input.value.trim();if(!value)return;const bubble=document.createElement('div');bubble.className='bubble user-bubble';bubble.innerHTML=`${value}<time>NOW</time>`;document.getElementById('chatBody').appendChild(bubble);input.value='';bubble.scrollIntoView({behavior:'smooth'});setTimeout(()=>notify('Message sent to Jordan'),250)});
document.querySelectorAll('.voucher').forEach(v=>v.addEventListener('click',()=>{document.querySelectorAll('.voucher').forEach(x=>x.classList.remove('selected'));v.classList.add('selected');document.getElementById('voucherValue').textContent=`£${v.dataset.value} gift voucher`}));document.getElementById('buyVoucher').addEventListener('click',()=>notify('Secure checkout opened for your voucher.'));

const videoModal=document.getElementById('videoModal'),youtubePlayer=document.getElementById('youtubePlayer'),videoModalTitle=document.getElementById('videoModalTitle'),youtubeLink=document.getElementById('youtubeLink');
function openVideo(id,title){videoModalTitle.textContent=title;youtubePlayer.src=`https://www.youtube-nocookie.com/embed/${id}?autoplay=1&rel=0`;youtubeLink.href=`https://www.youtube.com/watch?v=${id}`;videoModal.classList.add('open');videoModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeVideo(){videoModal.classList.remove('open');videoModal.setAttribute('aria-hidden','true');youtubePlayer.src='about:blank';document.body.style.overflow=''}
document.querySelectorAll('.video-open').forEach(button=>button.addEventListener('click',()=>openVideo(button.dataset.videoId,button.dataset.title)));
document.querySelector('.featured-play').addEventListener('click',()=>openVideo('gcNh17Ckjgg','How to properly squat for growth'));
document.querySelectorAll('[data-video-close]').forEach(button=>button.addEventListener('click',closeVideo));
const filterButtons=[...document.querySelectorAll('[data-filter]')],videoCards=[...document.querySelectorAll('.video-card')],videoSearch=document.getElementById('videoSearch');let activeFilter='all';
function filterVideos(){const query=videoSearch.value.trim().toLowerCase();let count=0;videoCards.forEach(card=>{const matchesCategory=activeFilter==='all'||card.dataset.category.includes(activeFilter);const matchesSearch=!query||card.dataset.search.includes(query)||card.textContent.toLowerCase().includes(query);const visible=matchesCategory&&matchesSearch;card.hidden=!visible;if(visible)count++});document.getElementById('videoCount').textContent=`${count} video${count===1?'':'s'}`;document.getElementById('videoEmpty').classList.toggle('show',count===0)}
filterButtons.forEach(button=>button.addEventListener('click',()=>{filterButtons.forEach(x=>x.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;filterVideos()}));videoSearch.addEventListener('input',filterVideos);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&videoModal.classList.contains('open'))closeVideo()});

const rewardButtons=[...document.querySelectorAll('[data-claim]')];let earnedXp=0;
try{earnedXp=Number(localStorage.getItem('form-earned-xp')||0)}catch(e){}
function renderRewards(){const total=2460+earnedXp;document.getElementById('currentXp').textContent=total.toLocaleString();document.getElementById('pointsTotal').textContent=total.toLocaleString();document.getElementById('leaderXp').textContent=`${total.toLocaleString()} XP`;document.getElementById('xpRemaining').textContent=`${Math.max(0,3000-total).toLocaleString()} XP`;document.getElementById('xpFill').style.width=`${Math.min(100,total/3000*100)}%`;rewardButtons.forEach((button,index)=>{let claimed=false;try{claimed=localStorage.getItem(`form-reward-${index}`)==='1'}catch(e){}if(claimed){button.textContent='Completed';button.disabled=true;button.closest('.challenge-card').classList.add('claimed')}})}
rewardButtons.forEach((button,index)=>button.addEventListener('click',()=>{if(button.disabled)return;const points=Number(button.dataset.claim);earnedXp+=points;try{localStorage.setItem('form-earned-xp',earnedXp);localStorage.setItem(`form-reward-${index}`,'1')}catch(e){}renderRewards();notify(`${button.dataset.action} · +${points} XP`)}));renderRewards();
